import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from './components/Sidebar'
import Navbar from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'E-Commerce Admin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar />
        <div className='flex flex-col left-72 w-[calc(100%-288px)] relative bg-light-gray min-h-screen'>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  )
}
